/* autogen */
#define FUNC_PRE_PLACE_HOLDER_OFFSET 116
#define FUNC_PRE_FILTER_ADDR_OFFSET 140
#define FUNC_PRE_ORIGIN_ADDR_OFFSET 148
#define FUNC_PRE_ERRNO_OFFSET 
#define FUNC_PRE_PATCH_INFO_CTX_OFFSET 156
#define FUNC_PRE_ATTACK_LOGGER_OFFSET 164
#define FUNC_PRE_RETURN_ADDR_OFFSET 
#define FUNC_POST_PLACE_HOLDER_OFFSET 32
#define FUNC_POST_FILTER_ADDR_OFFSET 152
#define FUNC_POST_ORIGIN_ADDR_OFFSET 160
#define FUNC_POST_ERRNO_OFFSET 
#define FUNC_POST_PATCH_INFO_CTX_OFFSET 168
#define FUNC_POST_ATTACK_LOGGER_OFFSET 176
#define FUNC_POST_RETURN_ADDR_OFFSET 
#define SUBFUNC_PRE_PLACE_HOLDER_OFFSET 
#define SUBFUNC_PRE_FILTER_ADDR_OFFSET 132
#define SUBFUNC_PRE_ORIGIN_ADDR_OFFSET 140
#define SUBFUNC_PRE_ERRNO_OFFSET 
#define SUBFUNC_PRE_PATCH_INFO_CTX_OFFSET 156
#define SUBFUNC_PRE_ATTACK_LOGGER_OFFSET 164
#define SUBFUNC_PRE_RETURN_ADDR_OFFSET 148
#define SUBFUNC_POST_PLACE_HOLDER_OFFSET 
#define SUBFUNC_POST_FILTER_ADDR_OFFSET 140
#define SUBFUNC_POST_ORIGIN_ADDR_OFFSET 132
#define SUBFUNC_POST_ERRNO_OFFSET 
#define SUBFUNC_POST_PATCH_INFO_CTX_OFFSET 148
#define SUBFUNC_POST_ATTACK_LOGGER_OFFSET 156
#define SUBFUNC_POST_RETURN_ADDR_OFFSET 
